# Generated by Django 5.1.7 on 2025-03-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('registro_ans', models.IntegerField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('ddd', models.CharField(blank=True, max_length=5, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_eletronico', models.CharField(blank=True, max_length=255, null=True)),
                ('representante', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('regiao_de_comercializacao', models.IntegerField(blank=True, null=True)),
                ('data_registro_ans', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
