version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    command: --secure-file-priv=""
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/data

volumes:
  mysql_data:
